# WARNING - Generated by {fusen} from /dev/dev_doc_fusen.Rmd: do not edit by hand

#' Render Word version of an xlsform
#' 
#' Us the built in template and functions from the package to generate a word 
#' version of the xlsform
#' 
#' @param dir directory where the xlsform is located
#' @param xlsformfile name of the file for the xlsform
#' @param label_language language to sue to generate the pretty print
#' @param wpm  word per minute - an average 180 word per minute (per default) 
#' required to read loudly the text
#' @param maxmodalities if more than 7 potential answers for a select question 
#' (per default)- then we assume that those modalities will not be read by the
#'  enumerator - but rather selected based on an open answer - and not be 
#'  accounted for the modalities duration estimation
#' @param resptimeclose  an average 4 seconds (per default) for respondent
#'  to reply for closed questions
#' @param resptimecondopen an average of  7 seconds (per default) to reply 
#' to conditional text question (accounting for question type of 
#' "other, please specify"). 
#' @param resptimeopen an average of  10 seconds (per default) to reply 
#' to open text question. 
#' @param avrgrepeat In case of repeat questions, an average 3 repeat 
#' (per default) is accounted for. 
#' 
#' @return a word document
#' 
#' @export
#' @examples
#' # render_prettyprint( dir =  system.file("", package = "XlsFormPrettyPrint"),
#' #   xlsformfile = "demo.xlsx",
#' #   label_language = NULL )
render_prettyprint <- function(  dir,
                                 xlsformfile,
                                 label_language  = NULL,
  # wpm  word per minute - an average 180 word per minute (per default) required to read loudly the text
  wpm  = 180, 
# maxmodalities if more than 7 potential answers for a select question (per default)- then we assume that those modalities will not be read by the enumerator - but rather selected based on an open answer - and not be accounted for the modalities duration estimation
  maxmodalities = 7 , 
# resptimeclose  an average 4 seconds (per default) for respondent to reply for closed questions
  resptimeclose  = 4,
# resptimecondopen an average of  7 seconds (per default) to reply to conditional text question (accounting for question type of "other, please specify"). 
  resptimecondopen = 7,
# resptimeopen an average of  10 seconds (per default) to reply to open text question. 
  resptimeopen = 10,
# avrgrepeat In case of repeat questions, an average 3 repeat (per default) is accounted for. 
  avrgrepeat = 3 ){
  
   rmarkdown::render(
    system.file("rmarkdown/templates/xlsform2word/skeleton/skeleton.Rmd", package = "XlsFormPrettyPrint"),
    output_file = here::here(dir, paste0('Pretty-', substr(xlsformfile,1, nchar(xlsformfile) -5) , '.docx') ),
    params = list( dir = dir,
                   xlsformfile =  xlsformfile, 
                  label_language = label_language,
  # wpm  word per minute - an average 180 word per minute (per default) required to read loudly the text
                  wpm  = 180, 
# maxmodalities if more than 7 potential answers for a select question (per default)- then we assume that those modalities will not be read by the enumerator - but rather selected based on an open answer - and not be accounted for the modalities duration estimation
                 maxmodalities = 7 , 
# resptimeclose  an average 4 seconds (per default) for respondent to reply for closed questions
                 resptimeclose  = 4,
# resptimecondopen an average of  7 seconds (per default) to reply to conditional text question (accounting for question type of "other, please specify"). 
                resptimecondopen = 7,
# resptimeopen an average of  10 seconds (per default) to reply to open text question. 
               resptimeopen = 10,
# avrgrepeat In case of repeat questions, an average 3 repeat (per default) is accounted for. 
               avrgrepeat = 3 )
)
    
}
