# WARNING - Generated by {fusen} from /dev/dev_doc_fusen.Rmd: do not edit by hand

#' @title Combine the xlsform in single table for pretty printing
#'
#' @param xlsformpath
#' 
#' @return a single data frame
#' @export
#' 
#' @examples
#' # tabulate_form()
#' 
#' prettyform <- tabulate_form( xlsformpath = system.file("demo.xlsx", package = "XlsFormPrettyPrint") )
#' 
#' knitr::kable(utils::head(prettyform, 10))
#' 
tabulate_form <- function(xlsformpath) {

  survey <- readxl::read_excel(xlsformpath, sheet = "survey")
  
  choices <- readxl::read_excel(xlsformpath, sheet = "choices") 
  
  settings <- readxl::read_excel(xlsformpath,  sheet = "settings")
  
  modalities <- choices |>
      ## Rename and use what ever label set is coming first 
      dplyr::rename(labelmod = dplyr::first(tidyselect::starts_with("label")),
                    namemod = name)  
    
  
  
  variables <-  survey |>
      ## Rename and use what ever label set is coming first 
      dplyr::rename(label = dplyr::first(tidyselect::starts_with("label")),
                    hint = dplyr::first(tidyselect::starts_with("hint")),
                    constraint_message = dplyr::first(tidyselect::starts_with("constraint_message"))) |>
      
      
      # Clean the begin and end in case the _ would be missing...
      dplyr::mutate(type = dplyr::recode(type, 
                                          "begin group" = "begin_group" ,
                                          "end group"   ="end_group",
                                         "begin repeat" = "begin_repeat" ,
                                         "end repeat"   ="end_repeat")) |>
      
      ## spearate the type
      tidyr::separate(type, 
                          into = c("type", "list_name"), 
                          sep = " ",
                          fill = "right")   |>
      
      # dplyr::mutate(name_type = glue::glue('{name} \n *(type: {type})')) |>
      # dplyr::mutate(label_hint = glue::glue('{label} \n *(hint: {hint})')) |>
      dplyr::mutate(name_type = paste0(name, "\n *(type: ",type, ")")) |>
      dplyr::mutate(label_hint = paste0( 
                                  dplyr::if_else(is.na(label), "no label", label),
                                  dplyr::if_else(is.na(hint), "", 
                                                 paste0("\n *(hint: ", hint, ")") 
                                                 ) )) |>
    
    
    ## Make the relevant expression more legible
      ## Case relevant if not null...
      dplyr::mutate(relevant = stringr::str_replace_all( relevant,
                                                         pattern = "''",
                                                         replacement = "NULL")) |>
      dplyr::mutate(relevant = stringr::str_replace_all( relevant,
                                                         pattern = "!=",
                                                         replacement = " is not ")) |>
      dplyr::mutate(relevant = dplyr::if_else(is.na(relevant), 
                                       relevant, 
                                       paste0(name, " is relevant if ", stringr::str_replace_all( relevant,
                                                        # pattern = c( "(", "\\$", "{", "}", ")" ),
                                                        pattern = "[^[:alnum:][:blank:]+?=_&/\\-]",
                                                         replacement = "")) )) |>
    
    ## Make the constraint expression more legible
     # dplyr::mutate(instruct = glue::glue('{relevant} \n *(constraint: {constraint_message})')) |>
      dplyr::mutate(instruct = paste0( 
                                  dplyr::if_else(is.na(relevant), "", relevant),
                                  dplyr::if_else(is.na(constraint_message), "", 
                                                 paste0("\n Constraint on ", name,": ", constraint_message, ")") 
                                                 ) )) |>
      
    ## Need to add more cleaning in case...
      dplyr::filter(!(is.na(type))) |>
      dplyr::filter(type != "calculate") |>
    
    ## Now merge with modalities
      dplyr::left_join(modalities, by = c("list_name")) |>
      dplyr::select(name_type ,label_hint, labelmod, namemod,  instruct) |>
      dplyr::distinct()
    
    return(variables)
    
}
 

