# WARNING - Generated by {fusen} from /dev/dev_doc_fusen.Rmd: do not edit by hand

#' @title Generate a consolidated xlsform from a list of xlsform in order to quickly flag differences
#' 
#' @description Note that comparison is done for a selected language
#'
#' @param listfile list of  path to multiple xlsform files - ll assumed to be in the same folder. The first one will be used as the master to compare the other to
#' 
#' @param folder where all the files are located
#' 
#' @param label_language Language to be used in case you have more than one. If not specified, the 'default_language' in the 'settings' worksheet is used. If that is not specified and more than one language is in the XlsForm, the language that comes first within column order will be used.
#' 
#' @param fileout  if specified defined the name of the file to save the xlsform_compare output
#' 
#' @return a file .
#' @export
#'
#' @examples
#' 
#' check <- xlsform_compare(listfile = c( "demo.xlsx","demo_adapt1.xlsx","demo_adapt2.xlsx"),  
#'                          folder = stringr::str_sub(system.file("", package = "XlsFormPrettyPrint"), end = -1) ,                    
#'                          label_language = NULL,
#'                          fileout = NULL)
#' 
#' # variablescompare,
#' knitr::kable(utils::head(as.data.frame(check[1]), 10))
#' # choicescompare
#' knitr::kable(utils::head(as.data.frame(check[2]), 10, 10))
#' 
xlsform_compare <- function( listfile,
                             folder,
                             label_language,
                             fileout = NULL) {
  # library(XlsFormPrettyPrint)
  formthis <- listfile[1]
  xlsformpath = here::here(folder, formthis)

  settings <- readxl::read_excel(xlsformpath,  sheet = "settings")
  #form_instance <- as.character(settings$form_title)

  ## Check if a default language is set up in the settings - and add the correct separator
  # for test settings$default_language <- NULL
  label_language <- ifelse( is.null(label_language),
                            ifelse( is.null(settings$default_language),
                                    label_language,
                                    paste0("::",settings$default_language)),
                            paste0("::",label_language))


  #### Choices master to... ######
  choicesmaster <- readxl::read_excel(xlsformpath, sheet = "choices") |>
    # dplyr::mutate(form_instance = form_instance)|>
    dplyr::mutate(form_file = stringr::str_remove(formthis, ".xlsx")) |>
    #  Rename and use what ever label set is coming first
    dplyr::rename(label = ifelse( is.null(label_language), dplyr::first(tidyselect::starts_with("label")), paste0("label",label_language)) ,
                  name = name) |>
    dplyr::filter(!(is.na(list_name))) |>
    dplyr::select(list_name ,name, label, form_file)
  
  
   
  survey <-  readxl::read_excel(xlsformpath, sheet = "survey")
    if ("required" %in% colnames(survey)) {   } else {    survey$required <- ""   }
    if ("relevant" %in% colnames(survey)) {   } else {    survey$relevant <- ""   }
    if ("constraint" %in% colnames(survey)) {   } else {    survey$constraint <- ""   }

  #### Variables master to... ######
  variablesmaster <-  survey |>
    ## Rename and use what ever label set is coming first
    dplyr::rename(label = ifelse( is.null(label_language), dplyr::first(tidyselect::starts_with("label")), paste0("label",label_language)),
                  hint =  ifelse( is.null(label_language), dplyr::first(tidyselect::starts_with("hint")), paste0("hint",label_language))  ) |>

    #dplyr::mutate(form_instance = form_instance)|>
    dplyr::mutate(form_file = stringr::str_remove(formthis, ".xlsx")) |>

    # Clean the begin and end in case the _ would be missing...
    dplyr::mutate(type = dplyr::recode(type,
                                       "begin group" = "begin_group" ,
                                       "end group"   ="end_group",
                                       "begin repeat" = "begin_repeat" ,
                                       "end repeat"   ="end_repeat")) |>

    ## separate the type
    tidyr::separate(type,
                    into = c("type", "list_name"),
                    sep = " ",
                    fill = "right")   |>

    # dplyr::mutate(name_type = glue::glue('{name} \n *(type: {type})')) |>
    # dplyr::mutate(label_hint = glue::glue('{label} \n *(hint: {hint})')) |>
    dplyr::mutate(name_type = paste0(name, "\n *(type: ",type, ")")) |>
    dplyr::mutate(label_hint = paste0(
      ifelse(is.na(label), "no label", label),
      ifelse(is.na(hint), "",
             paste0("\n *(hint: ", hint, ")")
      ) )) |>

    ## Need to add more cleaning in case...
    dplyr::filter(!(is.na(type))) |>
    dplyr::select(type, list_name, name, label, hint, required, relevant, constraint, 
                  form_file)

  ## initiate comparison
  choicescompare <- choicesmaster
  variablescompare <- variablesmaster

  #### Now looping around the list of file to compare the master to... ######
  for ( i in 2:length(listfile ))  {
    # i <- 2
    formthis <- listfile[i]
    cat(paste0(formthis, "\n\n"))
    xlsformpath = here::here(folder, formthis)
    #variables <- tabulate_form(xlsformpath, label_language )
    settings <- readxl::read_excel(xlsformpath,  sheet = "settings")
    #form_instance <- as.character(settings$form_title)
    choices <- readxl::read_excel(xlsformpath, sheet = "choices") |>
      # dplyr::mutate(form_instance = form_instance)|>
      dplyr::mutate(form_file = stringr::str_remove(formthis, ".xlsx")) |>
      #  Rename and use what ever label set is coming first
      dplyr::rename(label = ifelse( is.null(label_language), dplyr::first(tidyselect::starts_with("label")), paste0("label",label_language)) ,
                    name = name)  |>
      dplyr::filter(!(is.na(list_name))) |>
      dplyr::select(list_name ,name, label, form_file)

    ### Add & diff
    choicescompare <- dplyr::full_join(choicescompare, choices, by = c("list_name", "name"), suffix=c("",".diff") )|>
      dplyr::filter(!(is.na(list_name))) |>
      ##  clean the diff type comparison
      dplyr::mutate ( label.diff = dplyr::case_when(is.na(label) ~ label.diff,
                                                    is.na(label.diff) ~ "<<missing>>",
                                                    label.diff == label ~  NA_character_,
                                                    label.diff != label ~  label.diff )
                      #label.diff = dplyr::if_else(is.na(label),label.diff , dplyr::if_else( label.diff == label, NA_character_, label.diff ))
      )
    ## Rename diff based on type and file origin
    eval(parse(text=paste0("choicescompare$label.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- choicescompare$label.diff ") ))
    choicescompare$label.diff <- NULL
    choicescompare$form_file <- NULL
    choicescompare$form_file.diff <- NULL

    
    
    ## Now variable ####
      survey <-  readxl::read_excel(xlsformpath, sheet = "survey")
    if ("required" %in% colnames(survey)) {   } else {    survey$required <- ""   }
    if ("relevant" %in% colnames(survey)) {   } else {    survey$relevant <- ""   }
    if ("constraint" %in% colnames(survey)) {   } else {    survey$constraint <- ""   }
    
    variables <-  survey |>
      ## Rename and use what ever label set is coming first
      dplyr::rename(label = ifelse( is.null(label_language), dplyr::first(tidyselect::starts_with("label")), paste0("label",label_language)),
                    hint =  ifelse( is.null(label_language), dplyr::first(tidyselect::starts_with("hint")), paste0("hint",label_language))   ) |>
      #dplyr::mutate(form_instance = form_instance)|>
      dplyr::mutate(form_file = stringr::str_remove(formthis, ".xlsx")) |>
      # Clean the begin and end in case the _ would be missing...
      dplyr::mutate(type = dplyr::recode(type,
                                         "begin group" = "begin_group" ,
                                         "end group"   ="end_group",
                                         "begin repeat" = "begin_repeat" ,
                                         "end repeat"   ="end_repeat")) |>
      ## separate the type
      tidyr::separate(type,
                      into = c("type", "list_name"),
                      sep = " ",
                      fill = "right") |>
    ## Need to add more cleaning in case...
    dplyr::filter(!(is.na(type))) |>
    dplyr::select(type, list_name, name, label, hint, required, relevant, constraint,  form_file) #|>
    #dplyr::distinct()

    ### Add & diff
    variablescompare <- dplyr::full_join(variablescompare, variables, by = c( "name"), suffix=c("",".diff") ) |>
      dplyr::filter(!(is.na(name))) |>
      ##  clean the diff type comparison

      dplyr::mutate (type.diff = dplyr::case_when(is.na(type) ~ type.diff,
                                                  is.na(type.diff) ~ "<<missing>>",
                                                  type.diff == type ~  NA_character_ ,
                                                  type.diff != type ~ type.diff ) ,
                     list_name.diff = dplyr::case_when(is.na(list_name) ~ list_name.diff,
                                                       is.na(list_name.diff) ~ "<<missing>>",
                                                       list_name.diff == list_name ~ NA_character_,
                                                       list_name.diff != list_name ~  list_name.diff ),
                     label.diff = dplyr::case_when(is.na(label) ~ label.diff,
                                                   is.na(label.diff) ~ "<<missing>>",
                                                   label.diff == label ~  NA_character_,
                                                   label.diff != label ~  label.diff ),
                     hint.diff = dplyr::case_when(is.na(hint) ~ hint.diff,
                                                  is.na(hint.diff) ~ "<<missing>>",
                                                  hint.diff == hint ~  NA_character_,
                                                  hint.diff != hint ~  hint.diff ),
                     required.diff = dplyr::case_when(is.na(required) ~ required.diff,
                                                      is.na(required.diff) ~ "<<missing>>",
                                                      required.diff == required ~  NA_character_,
                                                      required.diff != required ~  required.diff ),
                     constraint.diff = dplyr::case_when(is.na(constraint) ~ constraint.diff,
                                                        is.na(constraint.diff) ~ "<<missing>>",
                                                        constraint.diff == constraint ~ NA_character_,
                                                        constraint.diff != constraint ~  constraint.diff ),
                     relevant.diff = dplyr::case_when(is.na(relevant) ~ relevant.diff,
                                                      is.na(relevant.diff) ~ "<<missing>>",
                                                      relevant.diff == relevant ~  NA_character_,
                                                      relevant.diff != type ~  relevant.diff ))





    # dplyr::mutate (type.diff = dplyr::if_else(is.na(type),type.diff , dplyr::if_else(type.diff == type, NA_character_, type.diff )),
    #                list_name.diff = dplyr::if_else(is.na(list_name),list_name.diff , dplyr::if_else( list_name.diff == list_name, NA_character_, list_name.diff )),
    #                label.diff = dplyr::if_else(is.na(label),label.diff , dplyr::if_else( label.diff == label, NA_character_, label.diff )),
    #                hint.diff = dplyr::if_else(is.na(hint),hint.diff , dplyr::if_else( hint.diff == hint, NA_character_, hint.diff )),
    #                required.diff = dplyr::if_else(is.na(required),required.diff , dplyr::if_else( required.diff == required, NA_character_, required.diff )),
    #                constraint.diff = dplyr::if_else(is.na(constraint),constraint.diff , dplyr::if_else( constraint.diff == constraint, NA_character_, constraint.diff )),
    #                relevant.diff = dplyr::if_else(is.na(relevant),relevant.diff , dplyr::if_else( relevant.diff == relevant, NA_character_, relevant.diff )))
    ## Rename diff based on type and file origin
    eval(parse(text=paste0("variablescompare$type.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$type.diff ") ))
    eval(parse(text=paste0("variablescompare$list_name.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$list_name.diff ") ))
    eval(parse(text=paste0("variablescompare$label.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$label.diff ") ))
    eval(parse(text=paste0("variablescompare$hint.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$hint.diff ") ))
    eval(parse(text=paste0("variablescompare$required.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$required.diff ") ))
    eval(parse(text=paste0("variablescompare$constraint.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$constraint.diff ") ))
    eval(parse(text=paste0("variablescompare$relevant.ifdiff.", stringr::str_remove(formthis, ".xlsx"), " <- variablescompare$relevant.diff ") ))
    #and remove previous column
    variablescompare$type.diff <- NULL
    variablescompare$list_name.diff <- NULL
    variablescompare$label.diff <- NULL
    variablescompare$hint.diff <- NULL
    variablescompare$required.diff <- NULL
    variablescompare$relevant.diff <- NULL
    variablescompare$constraint.diff <- NULL
    variablescompare$form_file <- NULL
    variablescompare$form_file.diff <- NULL

  }


  variablescompare <- variablescompare |>
    dplyr::select( name,
                   type,
                   starts_with("type.ifdiff."),
                   list_name,
                   starts_with("list_name.ifdiff."),
                   label,
                   starts_with("label.ifdiff."),
                   hint,
                   starts_with("hint.ifdiff."),
                   required,
                   starts_with("required.ifdiff."),
                   relevant,
                   starts_with("constraint.ifdiff."),
                   constraint,
                   starts_with("relevant.ifdiff")
    )

  choicescompare <- choicescompare |>
    dplyr::select( name,
                   list_name,
                   label,
                   starts_with("label.ifdiff.")  )

  # names(variablescompare)
  # names(choicescompare)

  ## Save in Excel if fileout is not null
  if ( !(is.null(fileout))) {
        ## Create a blank workbook
        wb <- openxlsx::createWorkbook()

        # Excel Styling Elements
        # To add filters for sheet, we have to set the range for addAutoFilter() function
        # EX: addAutoFilter(sheet1, "A1:P1") --> add a filter on the 1rd row, columns A:P
        # dfref dataframe allows to find 'P' based on number of columns in the sheet, if number of columns equal to 6 then the range will be A1:dfref[6,] -- A1:F1
        dfref <- data.frame(
          key = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256),
          val = c('A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1', 'I1', 'J1', 'K1', 'L1', 'M1', 'N1', 'O1', 'P1', 'Q1', 'R1', 'S1', 'T1', 'U1', 'V1', 'W1', 'X1', 'Y1', 'Z1', 'AA1', 'AB1', 'AC1', 'AD1', 'AE1', 'AF1', 'AG1', 'AH1', 'AI1', 'AJ1', 'AK1', 'AL1', 'AM1', 'AN1', 'AO1', 'AP1', 'AQ1', 'AR1', 'AS1', 'AT1', 'AU1', 'AV1', 'AW1', 'AX1', 'AY1', 'AZ1', 'BA1', 'BB1', 'BC1', 'BD1', 'BE1', 'BF1', 'BG1', 'BH1', 'BI1', 'BJ1', 'BK1', 'BL1', 'BM1', 'BN1', 'BO1', 'BP1', 'BQ1', 'BR1', 'BS1', 'BT1', 'BU1', 'BV1', 'BW1', 'BX1', 'BY1', 'BZ1', 'CA1', 'CB1', 'CC1', 'CD1', 'CE1', 'CF1', 'CG1', 'CH1', 'CI1', 'CJ1', 'CK1', 'CL1', 'CM1', 'CN1', 'CO1', 'CP1', 'CQ1', 'CR1', 'CS1', 'CT1', 'CU1', 'CV1', 'CW1', 'CX1', 'CY1', 'CZ1', 'DA1', 'DB1', 'DC1', 'DD1', 'DE1', 'DF1', 'DG1', 'DH1', 'DI1', 'DJ1', 'DK1', 'DL1', 'DM1', 'DN1', 'DO1', 'DP1', 'DQ1', 'DR1', 'DS1', 'DT1', 'DU1', 'DV1', 'DW1', 'DX1', 'DY1', 'DZ1', 'EA1', 'EB1', 'EC1', 'ED1', 'EE1', 'EF1', 'EG1', 'EH1', 'EI1', 'EJ1', 'EK1', 'EL1', 'EM1', 'EN1', 'EO1', 'EP1', 'EQ1', 'ER1', 'ES1', 'ET1', 'EU1', 'EV1', 'EW1', 'EX1', 'EY1', 'EZ1', 'FA1', 'FB1', 'FC1', 'FD1', 'FE1', 'FF1', 'FG1', 'FH1', 'FI1', 'FJ1', 'FK1', 'FL1', 'FM1', 'FN1', 'FO1', 'FP1', 'FQ1', 'FR1', 'FS1', 'FT1', 'FU1', 'FV1', 'FW1', 'FX1', 'FY1', 'FZ1', 'GA1', 'GB1', 'GC1', 'GD1', 'GE1', 'GF1', 'GG1', 'GH1', 'GI1', 'GJ1', 'GK1', 'GL1', 'GM1', 'GN1', 'GO1', 'GP1', 'GQ1', 'GR1', 'GS1', 'GT1', 'GU1', 'GV1', 'GW1', 'GX1', 'GY1', 'GZ1', 'HA1', 'HB1', 'HC1', 'HD1', 'HE1', 'HF1', 'HG1', 'HH1', 'HI1', 'HJ1', 'HK1', 'HL1', 'HM1', 'HN1', 'HO1', 'HP1', 'HQ1', 'HR1', 'HS1', 'HT1', 'HU1', 'HV1', 'HW1', 'HX1', 'HY1', 'HZ1', 'IA1', 'IB1', 'IC1', 'ID1', 'IE1', 'IF1', 'IG1', 'IH1', 'II1', 'IJ1', 'IK1', 'IL1', 'IM1', 'IN1', 'IO1', 'IP1', 'IQ1', 'IR1', 'IS1', 'IT1', 'IU1', 'IV1')
        )

        #For better legibility create specific styles for rows that defines header
        headerSt <- openxlsx::createStyle( textDecoration = "bold", fontColour = "white", fontSize = 13, fgFill = "grey50",
                                           border = "TopBottom", borderColour = "grey80", borderStyle = "thin")
        #For better legibility create specific styles for rows that defines groups
        cs1 <- openxlsx::createStyle( textDecoration = "bold", fontColour = "black", fgFill = "orange",
                                      border = "TopBottom", borderColour = "orange", borderStyle = "thin")
        #For better legibility create specific styles for rows that defines repeat
        cs2 <- openxlsx::createStyle( textDecoration = "bold", fontColour = "white", fgFill = "skyblue",
                                      border = "TopBottom", borderColour = "skyblue", borderStyle = "thin")
        sheetname <- "variablescompare"
        openxlsx::addWorksheet(wb, sheetname)
        openxlsx::writeData(wb, sheetname, variablescompare, withFilter = TRUE)
        openxlsx::setColWidths(wb, sheetname, cols = 1:ncol(variablescompare), widths = "auto")
        all.cols <- 1:ncol(variablescompare)
        hdr.rows <- 1
        group.rows <- which(stringr::str_detect(variablescompare$type, "group"))+1
        repeat.rows <- which(stringr::str_detect(variablescompare$type, "repeat"))+1
        openxlsx::addStyle(wb, sheetname, headerSt, hdr.rows, all.cols, gridExpand = TRUE)
        openxlsx::addStyle(wb, sheetname, cs1, group.rows, all.cols, gridExpand = TRUE)
        openxlsx::addStyle(wb, sheetname, cs2, repeat.rows, all.cols, gridExpand = TRUE)

        sheetname <- "choicescompare"
        openxlsx::addWorksheet(wb, sheetname)
        openxlsx::writeData(wb, sheetname, choicescompare, withFilter = TRUE)
        openxlsx::setColWidths(wb, sheetname, cols = 1:ncol(choicescompare), widths = "auto")

        xlsformpathout <- here::here(folder,fileout)
       # wb
        if (file.exists(xlsformpathout)) file.remove(xlsformpathout)
        cat( paste0(xlsformpathout,"\n"))
        openxlsx::saveWorkbook(wb, file = xlsformpathout, overwrite = FALSE, returnValue = FALSE)
  }

  diffinform <-list(variablescompare,choicescompare )
  return(diffinform)

}
 

